# Generated by Django 3.0.3 on 2020-03-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforseo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordfinder',
            name='depth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Profundidad'),
        ),
        migrations.AddField(
            model_name='keywordfinder',
            name='filters',
            field=models.TextField(blank=True, null=True, verbose_name='Filtros'),
        ),
        migrations.AddField(
            model_name='keywordfinder',
            name='keyword',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Keyword'),
        ),
        migrations.AddField(
            model_name='keywordfinder',
            name='language',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Idioma/País'),
        ),
        migrations.AddField(
            model_name='keywordfinder',
            name='limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Límite'),
        ),
        migrations.AddField(
            model_name='keywordfinder',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado'),
        ),
    ]
