# Generated by Django 3.0.3 on 2020-03-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataforseo', '0002_auto_20200331_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordfinder',
            options={'verbose_name': 'Keywordfinder', 'verbose_name_plural': 'Keywordfinders'},
        ),
    ]
