# Generated by Django 3.0.3 on 2020-03-31 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataforseo', '0003_auto_20200331_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeywordFinder',
            new_name='KeywordSearch',
        ),
        migrations.AlterModelOptions(
            name='keywordsearch',
            options={'verbose_name': 'KeywordSearch', 'verbose_name_plural': 'KeywordSearch'},
        ),
    ]
