# Generated by Django 3.0.3 on 2020-06-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataforseo', '0007_auto_20200630_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeywordBulk',
            new_name='KeywordList',
        ),
    ]
